# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'people',
  dependencies = [
    'src/main/scala/com/foursquare/spindle/runtime',
  ],
  sources = globs('*.thrift'),
)
