# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'runtime',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:finagle',
    '3rdparty:jackson',
    '3rdparty:joda-time',
    '3rdparty:junit',
    '3rdparty:phonenumbers',
    '3rdparty:specs',
    '3rdparty:twitter-util',
    'src/test/thrift/com/foursquare/spindle/codegen',
    'src/test/thrift/com/foursquare/thriftexample',
  ],
)
