# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

spindle_thrift_library(
  name = 'av',
  dependencies = [
    'src/main/scala/com/foursquare/spindle/runtime',
    'src/test/thrift/com/foursquare/thriftexample/talent',
  ],
  sources = globs('*.thrift'),
)
