# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'binary',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:jackson',
    '3rdparty:joda-time',
    '3rdparty:junit',
    '3rdparty:scala-compiler',
    'src/main/java/com/foursquare/common/thrift/base',
    'src/main/java/com/foursquare/common/thrift/json',
    'src/main/scala/com/foursquare/spindle/codegen/binary',
  ],
)
