# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

java_library(
  name = 'parser',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:argot',
    '3rdparty:commons-io',
    '3rdparty:joda-time',
    '3rdparty:parboiled-scala',
    '3rdparty:thrift',
    '3rdparty:rogue-field',
    'src/main/thrift/com/twitter/thrift/descriptors',
  ],
)
