# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

java_library(
  name = 'json',
  sources = globs('*.java'),
  dependencies = [
    '3rdparty:jackson',
    '3rdparty:joda-time',
    'src/main/java/com/foursquare/common/thrift/base',
  ],
)
