# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

java_library(
  name = 'runtime',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:thrift',
    '3rdparty:rogue-field',
    'src/main/java/com/foursquare/common/thrift/base',
    'src/main/java/com/foursquare/common/thrift/bson',
    'src/main/java/com/foursquare/common/thrift/json',
  ],
)
