# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

java_library(
  name = 'bson',
  sources = globs('*.java'),
  dependencies = [
    '3rdparty:thrift',
    '3rdparty:mongodb',
    'src/main/java/com/foursquare/common/thrift/base',
  ],
)
