# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

java_library(
  name = 'base',
  sources = globs('*.java'),
  dependencies = [
    '3rdparty:joda-time',
    '3rdparty:thrift',
  ],
  provides = artifact(
    org='com.foursquare',
    name='common-thrift-base',
    repo=internal_repo,
  ),
)
