# Copyright 2015 Foursquare Labs Inc. All Rights Reserved.

junit_tests(
  name = 'parser',
  sources = globs('*.scala'),
  dependencies = [
    '3rdparty:jackson',
    '3rdparty:joda-time',
    '3rdparty:junit',
    'src/main/scala/com/foursquare/spindle/codegen/parser',
  ],
)
