
/**
 * GENERATED CODE - DO NOT EDIT!
 * Generated by foursquare.thrift.codegen
 *

 */


package com.twitter.thrift.descriptors;

class java_thrift_descriptors {

public static interface JavaSimpleBaseType {
  public abstract int id();
  public int getValue();
}

public static interface JavaRequiredness {
  public abstract int id();
  public int getValue();
}

public static abstract class JavaIncludeMeta { }

public static interface JavaInclude { }

public static interface JavaIncludeMutable extends JavaInclude { }

public static abstract class JavaIncludeRaw implements JavaIncludeMutable { }
public static abstract class JavaNamespaceMeta { }

public static interface JavaNamespace { }

public static interface JavaNamespaceMutable extends JavaNamespace { }

public static abstract class JavaNamespaceRaw implements JavaNamespaceMutable { }
public static abstract class JavaAnnotationMeta { }

public static interface JavaAnnotation { }

public static interface JavaAnnotationMutable extends JavaAnnotation { }

public static abstract class JavaAnnotationRaw implements JavaAnnotationMutable { }
public static abstract class JavaBaseTypeMeta { }

public static interface JavaBaseType { }

public static interface JavaBaseTypeMutable extends JavaBaseType { }

public static abstract class JavaBaseTypeRaw implements JavaBaseTypeMutable { }
public static abstract class JavaListTypeMeta { }

public static interface JavaListType { }

public static interface JavaListTypeMutable extends JavaListType { }

public static abstract class JavaListTypeRaw implements JavaListTypeMutable { }
public static abstract class JavaSetTypeMeta { }

public static interface JavaSetType { }

public static interface JavaSetTypeMutable extends JavaSetType { }

public static abstract class JavaSetTypeRaw implements JavaSetTypeMutable { }
public static abstract class JavaMapTypeMeta { }

public static interface JavaMapType { }

public static interface JavaMapTypeMutable extends JavaMapType { }

public static abstract class JavaMapTypeRaw implements JavaMapTypeMutable { }
public static abstract class JavaContainerTypeMeta { }

public static interface JavaContainerType { }

public static interface JavaContainerTypeMutable extends JavaContainerType { }

public static abstract class JavaContainerTypeRaw implements JavaContainerTypeMutable { }
public static abstract class JavaTyperefMeta { }

public static interface JavaTyperef { }

public static interface JavaTyperefMutable extends JavaTyperef { }

public static abstract class JavaTyperefRaw implements JavaTyperefMutable { }
public static abstract class JavaTypeMeta { }

public static interface JavaType { }

public static interface JavaTypeMutable extends JavaType { }

public static abstract class JavaTypeRaw implements JavaTypeMutable { }
public static abstract class JavaTypedefMeta { }

public static interface JavaTypedef { }

public static interface JavaTypedefMutable extends JavaTypedef { }

public static abstract class JavaTypedefRaw implements JavaTypedefMutable { }
public static abstract class JavaTypeRegistryMeta { }

public static interface JavaTypeRegistry { }

public static interface JavaTypeRegistryMutable extends JavaTypeRegistry { }

public static abstract class JavaTypeRegistryRaw implements JavaTypeRegistryMutable { }
public static abstract class JavaConstMeta { }

public static interface JavaConst { }

public static interface JavaConstMutable extends JavaConst { }

public static abstract class JavaConstRaw implements JavaConstMutable { }
public static abstract class JavaEnumElementMeta { }

public static interface JavaEnumElement { }

public static interface JavaEnumElementMutable extends JavaEnumElement { }

public static abstract class JavaEnumElementRaw implements JavaEnumElementMutable { }
public static abstract class JavaEnumMeta { }

public static interface JavaEnum { }

public static interface JavaEnumMutable extends JavaEnum { }

public static abstract class JavaEnumRaw implements JavaEnumMutable { }
public static abstract class JavaFieldMeta { }

public static interface JavaField { }

public static interface JavaFieldMutable extends JavaField { }

public static abstract class JavaFieldRaw implements JavaFieldMutable { }
public static abstract class JavaStructMeta { }

public static interface JavaStruct { }

public static interface JavaStructMutable extends JavaStruct { }

public static abstract class JavaStructRaw implements JavaStructMutable { }
public static abstract class JavaUnionMeta { }

public static interface JavaUnion { }

public static interface JavaUnionMutable extends JavaUnion { }

public static abstract class JavaUnionRaw implements JavaUnionMutable { }
public static abstract class JavaExceptionMeta { }

public static interface JavaException { }

public static interface JavaExceptionMutable extends JavaException { }

public static abstract class JavaExceptionRaw implements JavaExceptionMutable { }
public static abstract class JavaFunctionMeta { }

public static interface JavaFunction { }

public static interface JavaFunctionMutable extends JavaFunction { }

public static abstract class JavaFunctionRaw implements JavaFunctionMutable { }
public static abstract class JavaServiceMeta { }

public static interface JavaService { }

public static interface JavaServiceMutable extends JavaService { }

public static abstract class JavaServiceRaw implements JavaServiceMutable { }
public static abstract class JavaProgramMeta { }

public static interface JavaProgram { }

public static interface JavaProgramMutable extends JavaProgram { }

public static abstract class JavaProgramRaw implements JavaProgramMutable { }


public static abstract class JavaSimpleContainerTypeMeta { }

public static interface JavaSimpleContainerType { }

public static interface JavaSimpleContainerTypeMutable extends JavaSimpleContainerType { }

public static abstract class JavaSimpleContainerTypeRaw implements JavaSimpleContainerTypeMutable { }

public static abstract class JavaSimpleTypeMeta { }

public static interface JavaSimpleType { }

public static interface JavaSimpleTypeMutable extends JavaSimpleType { }

public static abstract class JavaSimpleTypeRaw implements JavaSimpleTypeMutable { }


}
